### PR TITLE
Add modifiers for specification value

### PR DESCRIPTION
**Pull request by stellassantos**
#### What problem is this solving?
Don't have a handle with the specification value 

I  need to show a specific picture for values and I need classes for this values

#### How to test it?
https://devstella--zonasul.myvtex.com/

[Workspace](Link goes here!)

#### Screenshots or example usage:
image

### CODE REVIEW

**Comment by stellassantos** [comment]
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

**Review by guerreirobeatriz — APPROVED** [review]

**Review by kaisermann — APPROVED** [review]

**Review by klzns — CHANGES_REQUESTED** [review]
Thanks for contributing!

Missing changelog entry.

Please add this below the [Unreleased] section of the CHANGELOG.md file:

```diff
 ## [Unreleased]
+### Added
+- CSS Handles to specification value.
```

**Comment by klzns** [comment]
Btw, why not use the [vtex.product-specifications](https://github.com/vtex-apps/product-specifications) app? It's more flexible than this one and you can achieve the same things

**Comment by stellassantos** [comment]
> Btw, why not use the [vtex.product-specifications](https://github.com/vtex-apps/product-specifications) app? It's more flexible than this one and you can achieve the same things

Na verdade eu estou usando o product-summary-specification-badges pra criar flags especificas de acordo com o especificação do produto e exibindo elas por imagem em cima da imagem da vitrine com stack-layout, eu conseguiria usar da mesma forma o vtex.product-specifications?

**Review by icazevedo — APPROVED** [review]

**Review by vitorflg — APPROVED** [review]

**Comment by stellinhastar** [comment]
> Thanks for contributing!
> 
> Missing changelog entry.
> 
> Please add this below the [Unreleased] section of the CHANGELOG.md file:
> 
> ```diff
>  ## [Unreleased]
> +### Added
> +- CSS Handles to specification value.
> ```

**Comment by klzns** [comment]
@stellinhastar sim, conseguiria!

**Review by klzns — APPROVED** [review]

**Pull request merged**
